"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import { BackgroundBeamsWithCollisionDemo } from "@/components/landingPage/BackgroundBeamsWithCollisionDemo";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black ${inter.className}`}>
      <div className="fixed inset-0 z-0">
          <BackgroundBeamsWithCollisionDemo/>
        </div>
      <div className="relative z-10">
          <Navbar/>
          {children}
          <Footer/>
          </div>
      </body>
    </html>
  );
}